# Generated by Django 5.1.15 on 2026-03-05 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("processing", "En traitement"),
                            ("indexed", "Indexé"),
                            ("failed", "Échoué"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenancy.knowledgespace",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("file_name", models.CharField(max_length=500)),
                ("file_path", models.CharField(max_length=1000)),
                ("mime_type", models.CharField(default="application/pdf", max_length=100)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("file_hash", models.CharField(blank=True, default="", max_length=64)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "indexing_status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("processing", "En traitement"),
                            ("indexed", "Indexé"),
                            ("failed", "Échoué"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="documents.document"
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de document",
                "verbose_name_plural": "Versions de document",
                "db_table": "document_versions",
                "ordering": ["-version_number"],
                "unique_together": {("document", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="DocumentProcessingJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("index", "Indexation"),
                            ("reindex", "Réindexation"),
                            ("delete_index", "Suppression index"),
                        ],
                        default="index",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("running", "En cours"),
                            ("succeeded", "Réussi"),
                            ("failed", "Échoué"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job de traitement",
                "verbose_name_plural": "Jobs de traitement",
                "db_table": "document_processing_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
