# Generated by Django 5.1.15 on 2026-03-05 21:39

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("embedding", pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "knowledge_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_chunks",
                        to="tenancy.knowledgespace",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="document_chunks", to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk de document",
                "verbose_name_plural": "Chunks de document",
                "db_table": "document_chunks",
                "ordering": ["chunk_index"],
                "indexes": [models.Index(fields=["tenant", "knowledge_space"], name="document_ch_tenant__6536d6_idx")],
                "unique_together": {("document_version", "chunk_index")},
            },
        ),
    ]
